-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.dim_brick
(
    brick_id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    cod_brick integer NOT NULL,
    nome_brick character varying(150) COLLATE pg_catalog."default" NOT NULL,
    regiao_comercial character varying(100) COLLATE pg_catalog."default",
    macro_regiao character varying(100) COLLATE pg_catalog."default",
    descricao character varying(255) COLLATE pg_catalog."default",
    ativo boolean DEFAULT true,
    data_criacao timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    data_atualizacao timestamp without time zone,
    CONSTRAINT dim_brick_pkey PRIMARY KEY (brick_id),
    CONSTRAINT dim_brick_cod_brick_key UNIQUE (cod_brick)
);

CREATE TABLE IF NOT EXISTS public.dim_empresa
(
    empresa_id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    cod_empresa integer NOT NULL,
    nome_empresa character varying(200) COLLATE pg_catalog."default" NOT NULL,
    cnpj character varying(20) COLLATE pg_catalog."default",
    razao_social character varying(200) COLLATE pg_catalog."default",
    nome_fantasia character varying(200) COLLATE pg_catalog."default",
    insc_estadual character varying(30) COLLATE pg_catalog."default",
    insc_municipal character varying(30) COLLATE pg_catalog."default",
    endereco_id bigint,
    ativo boolean DEFAULT true,
    data_criacao timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT dim_empresa_pkey PRIMARY KEY (empresa_id),
    CONSTRAINT dim_empresa_cod_empresa_key UNIQUE (cod_empresa)
);

CREATE TABLE IF NOT EXISTS public.dim_endereco
(
    endereco_id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    cep character varying(9) COLLATE pg_catalog."default" NOT NULL,
    rua character varying(150) COLLATE pg_catalog."default" NOT NULL,
    numero character varying(10) COLLATE pg_catalog."default",
    bairro character varying(100) COLLATE pg_catalog."default",
    cidade character varying(100) COLLATE pg_catalog."default" NOT NULL,
    estado character(2) COLLATE pg_catalog."default" NOT NULL,
    ativo boolean DEFAULT true,
    data_criacao timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    data_atualizacao timestamp without time zone,
    CONSTRAINT dim_endereco_pkey PRIMARY KEY (endereco_id)
);

CREATE TABLE IF NOT EXISTS public.dim_filial
(
    filial_id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    cod_filial integer NOT NULL,
    nome_filial character varying(150) COLLATE pg_catalog."default" NOT NULL,
    empresa_id bigint NOT NULL,
    endereco_id bigint NOT NULL,
    tipo_filial character varying(50) COLLATE pg_catalog."default",
    status_operacao character varying(50) COLLATE pg_catalog."default",
    ativo boolean DEFAULT true,
    data_criacao timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    data_atualizacao timestamp without time zone,
    CONSTRAINT dim_filial_pkey PRIMARY KEY (filial_id),
    CONSTRAINT dim_filial_cod_filial_key UNIQUE (cod_filial)
);

CREATE TABLE IF NOT EXISTS public.dim_filial_brick
(
    filial_brick_id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    filial_id bigint NOT NULL,
    brick_id bigint NOT NULL,
    data_criacao timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    ativo boolean DEFAULT true,
    CONSTRAINT dim_filial_brick_pkey PRIMARY KEY (filial_brick_id)
);

CREATE TABLE IF NOT EXISTS public.dim_produto
(
    produto_id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    cod_produto_catarinense character varying(20) COLLATE pg_catalog."default",
    ean character varying(20) COLLATE pg_catalog."default",
    nome_produto_catarinense character varying(300) COLLATE pg_catalog."default" NOT NULL,
    data_criacao timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    ativo boolean DEFAULT true,
    CONSTRAINT dim_produto_pkey PRIMARY KEY (produto_id),
    CONSTRAINT uq_dim_produto_cods UNIQUE (produto_id, ean, cod_produto_catarinense),
    CONSTRAINT uq_produto_ean UNIQUE (ean)
);

CREATE TABLE IF NOT EXISTS public.fact_vendas_iqvia
(
    fact_vendas_iqvia_id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    vol_concorrente_indep numeric(18, 4),
    vol_concorrente_rede numeric(18, 4),
    vol_marca_pp numeric(18, 4),
    vol_total_mercado numeric(18, 4),
    participacao_clamed numeric(18, 4),
    cod_brick integer,
    ean character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT fact_vendas_iqvia_pkey PRIMARY KEY (fact_vendas_iqvia_id)
);

ALTER TABLE IF EXISTS public.dim_empresa
    ADD CONSTRAINT fk_dim_empresa_endereco FOREIGN KEY (endereco_id)
    REFERENCES public.dim_endereco (endereco_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.dim_filial
    ADD CONSTRAINT fk_dim_filial_empresa FOREIGN KEY (empresa_id)
    REFERENCES public.dim_empresa (empresa_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.dim_filial
    ADD CONSTRAINT fk_dim_filial_endereco FOREIGN KEY (endereco_id)
    REFERENCES public.dim_endereco (endereco_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.dim_filial_brick
    ADD CONSTRAINT fk_filial_brick_brick FOREIGN KEY (brick_id)
    REFERENCES public.dim_brick (brick_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.dim_filial_brick
    ADD CONSTRAINT fk_filial_brick_filial FOREIGN KEY (filial_id)
    REFERENCES public.dim_filial (filial_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.fact_vendas_iqvia
    ADD CONSTRAINT fk_fact_brick FOREIGN KEY (cod_brick)
    REFERENCES public.dim_brick (cod_brick) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.fact_vendas_iqvia
    ADD CONSTRAINT fk_fact_produto_ean FOREIGN KEY (ean)
    REFERENCES public.dim_produto (ean) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;